version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mock-api-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    networks:
      - mock-api-network
    command: mvn spring-boot:run

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mock-api-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mock-api-network
    command: npm start

networks:
  mock-api-network:
    driver: bridge
